import type { AnalysisDetail } from "./types";

/** Escape pipes so a requirement containing one cannot break the table. */
function cell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\n+/g, " ").trim();
}

/**
 * Serialise a whole report to Markdown, for pasting into notes, a ticket or a
 * message to whoever is reviewing the CV.
 */
export function analysisToMarkdown(result: AnalysisDetail, title?: string): string {
  const { analysis, sub_scores, cv_scores } = result;
  const lines: string[] = [];

  lines.push(`# VacancyScore report${title ? `: ${title}` : ""}`);
  lines.push("");
  lines.push(`**Fit score:** ${analysis.fit_score}/100 — ${analysis.fit_label}`);
  lines.push(`**Recommended CV:** ${result.recommended_cv_label}`);
  lines.push(
    `**Sub-scores:** profile ${sub_scores.profile}% · skills ${sub_scores.skills}% · summary ${sub_scores.summary}%`,
  );
  lines.push("");
  lines.push(analysis.summary);

  lines.push("", "## CV ranking", "");
  for (const score of cv_scores) {
    const marker = score.cv_id === result.recommended_cv?.id ? " ← recommended" : "";
    lines.push(`- ${score.label}: ${score.similarity.toFixed(0)}%${marker}`);
  }

  lines.push("", "## Matched keywords", "");
  if (analysis.matched_keywords.length === 0) {
    lines.push("_None._");
  } else {
    for (const item of analysis.matched_keywords) {
      lines.push(`- ${item.keyword} (${item.location})`);
    }
  }

  lines.push("", "## Missing keywords", "");
  lines.push(
    analysis.missing_keywords.length === 0
      ? "_None._"
      : analysis.missing_keywords.map((k) => `- ${k}`).join("\n"),
  );

  lines.push("", "## Gaps", "");
  if (analysis.gaps.length === 0) {
    lines.push("_No gaps found._");
  } else {
    lines.push("| Requirement | Your CV shows | Severity | Suggested fix |");
    lines.push("| --- | --- | --- | --- |");
    for (const gap of analysis.gaps) {
      lines.push(
        `| ${cell(gap.requirement)} | ${cell(gap.cv_evidence) || "—"} | ${gap.severity} | ${cell(gap.suggested_fix)} |`,
      );
    }
  }

  lines.push("", "## Do these edits", "");
  lines.push(
    analysis.tips.length === 0
      ? "_No edits suggested._"
      : analysis.tips.map((tip) => `- [ ] ${tip}`).join("\n"),
  );

  lines.push("", "---", "", `_Generated by VacancyScore on ${new Date(result.created_at).toLocaleString()}._`);

  return lines.join("\n");
}
